package com.tm.broadband.mapper;

import com.tm.broadband.model.CallingRecord;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallingRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calling_record
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calling_record
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	int insert(CallingRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calling_record
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	CallingRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calling_record
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	List<CallingRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calling_record
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	int updateByPrimaryKey(CallingRecord record);
}