package com.tm.broadband.mapper;

import com.tm.broadband.model.UploadedFile;
import java.util.List;

public interface UploadedFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    int deleteById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    int insert(UploadedFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    UploadedFile selectById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    List<UploadedFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    int updateById(UploadedFile record);
}