package com.tm.broadband.model;

import java.util.Date;

public class AddonServiceRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.fileId
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer fileid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.ori_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String oriNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.date_from
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Date dateFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.date_to
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Date dateTo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.cost
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Double cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.charge
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Double charge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.order_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.invoice_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer invoiceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_addon_service_record.description
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.id
	 * @return  the value of t_addon_service_record.id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.id
	 * @param id  the value for t_addon_service_record.id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.fileId
	 * @return  the value of t_addon_service_record.fileId
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getFileid() {
		return fileid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.fileId
	 * @param fileid  the value for t_addon_service_record.fileId
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setFileid(Integer fileid) {
		this.fileid = fileid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.ori_number
	 * @return  the value of t_addon_service_record.ori_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getOriNumber() {
		return oriNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.ori_number
	 * @param oriNumber  the value for t_addon_service_record.ori_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setOriNumber(String oriNumber) {
		this.oriNumber = oriNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.date_from
	 * @return  the value of t_addon_service_record.date_from
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Date getDateFrom() {
		return dateFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.date_from
	 * @param dateFrom  the value for t_addon_service_record.date_from
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.date_to
	 * @return  the value of t_addon_service_record.date_to
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Date getDateTo() {
		return dateTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.date_to
	 * @param dateTo  the value for t_addon_service_record.date_to
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.cost
	 * @return  the value of t_addon_service_record.cost
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Double getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.cost
	 * @param cost  the value for t_addon_service_record.cost
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setCost(Double cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.charge
	 * @return  the value of t_addon_service_record.charge
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Double getCharge() {
		return charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.charge
	 * @param charge  the value for t_addon_service_record.charge
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setCharge(Double charge) {
		this.charge = charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.order_id
	 * @return  the value of t_addon_service_record.order_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.order_id
	 * @param orderId  the value for t_addon_service_record.order_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.invoice_id
	 * @return  the value of t_addon_service_record.invoice_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getInvoiceId() {
		return invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.invoice_id
	 * @param invoiceId  the value for t_addon_service_record.invoice_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_addon_service_record.description
	 * @return  the value of t_addon_service_record.description
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_addon_service_record.description
	 * @param description  the value for t_addon_service_record.description
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}