package com.tm.broadband.model;

import java.util.Date;

public class CallingRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.fileId
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer fileid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.ori_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String oriNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.call_start
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Date callStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.duration
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.cost
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Double cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.charge
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Double charge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.des_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String desNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.area_prefix
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String areaPrefix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.type
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.order_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.invoice_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private Integer invoiceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calling_record.description
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.id
	 * @return  the value of t_calling_record.id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.id
	 * @param id  the value for t_calling_record.id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.fileId
	 * @return  the value of t_calling_record.fileId
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getFileid() {
		return fileid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.fileId
	 * @param fileid  the value for t_calling_record.fileId
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setFileid(Integer fileid) {
		this.fileid = fileid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.ori_number
	 * @return  the value of t_calling_record.ori_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getOriNumber() {
		return oriNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.ori_number
	 * @param oriNumber  the value for t_calling_record.ori_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setOriNumber(String oriNumber) {
		this.oriNumber = oriNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.call_start
	 * @return  the value of t_calling_record.call_start
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Date getCallStart() {
		return callStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.call_start
	 * @param callStart  the value for t_calling_record.call_start
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setCallStart(Date callStart) {
		this.callStart = callStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.duration
	 * @return  the value of t_calling_record.duration
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.duration
	 * @param duration  the value for t_calling_record.duration
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.cost
	 * @return  the value of t_calling_record.cost
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Double getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.cost
	 * @param cost  the value for t_calling_record.cost
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setCost(Double cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.charge
	 * @return  the value of t_calling_record.charge
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Double getCharge() {
		return charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.charge
	 * @param charge  the value for t_calling_record.charge
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setCharge(Double charge) {
		this.charge = charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.des_number
	 * @return  the value of t_calling_record.des_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getDesNumber() {
		return desNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.des_number
	 * @param desNumber  the value for t_calling_record.des_number
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setDesNumber(String desNumber) {
		this.desNumber = desNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.area_prefix
	 * @return  the value of t_calling_record.area_prefix
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getAreaPrefix() {
		return areaPrefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.area_prefix
	 * @param areaPrefix  the value for t_calling_record.area_prefix
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setAreaPrefix(String areaPrefix) {
		this.areaPrefix = areaPrefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.type
	 * @return  the value of t_calling_record.type
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.type
	 * @param type  the value for t_calling_record.type
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.order_id
	 * @return  the value of t_calling_record.order_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.order_id
	 * @param orderId  the value for t_calling_record.order_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.invoice_id
	 * @return  the value of t_calling_record.invoice_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public Integer getInvoiceId() {
		return invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.invoice_id
	 * @param invoiceId  the value for t_calling_record.invoice_id
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calling_record.description
	 * @return  the value of t_calling_record.description
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calling_record.description
	 * @param description  the value for t_calling_record.description
	 * @mbggenerated  Wed Dec 02 03:34:08 NZDT 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}