package com.tm.broadband.model;

import java.util.Date;

public class UploadedFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.id
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.file_name
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.ori_file_name
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    private String oriFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.type
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.upload_by
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    private Integer uploadBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.upload_date
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    private Date uploadDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.id
     *
     * @return the value of t_uploaded_file.id
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.id
     *
     * @param id the value for t_uploaded_file.id
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.file_name
     *
     * @return the value of t_uploaded_file.file_name
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.file_name
     *
     * @param fileName the value for t_uploaded_file.file_name
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.ori_file_name
     *
     * @return the value of t_uploaded_file.ori_file_name
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public String getOriFileName() {
        return oriFileName;
    }
    
    public String getFileName(){
    	return this.id + this.extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.ori_file_name
     *
     * @param oriFileName the value for t_uploaded_file.ori_file_name
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public void setOriFileName(String oriFileName) {
        this.oriFileName = oriFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.type
     *
     * @return the value of t_uploaded_file.type
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.type
     *
     * @param type the value for t_uploaded_file.type
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.upload_by
     *
     * @return the value of t_uploaded_file.upload_by
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public Integer getUploadBy() {
        return uploadBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.upload_by
     *
     * @param uploadBy the value for t_uploaded_file.upload_by
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public void setUploadBy(Integer uploadBy) {
        this.uploadBy = uploadBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.upload_date
     *
     * @return the value of t_uploaded_file.upload_date
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.upload_date
     *
     * @param uploadDate the value for t_uploaded_file.upload_date
     *
     * @mbggenerated Mon Nov 30 16:45:18 NZDT 2015
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }
}